name: Futureurban.co.nz
favicon: null
layout_spectrum: 0.675876323133707
typography_spectrum: 0.9985874621197581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6001558147836477
  lightness: 0.8608209080994129
  saturation: 0.5572533605154604
  rhythmicContrast: 0.47192795295268297
purpose: []
