name: Futureurban.co.nz
favicon: null
layout_spectrum: 0.675876323133707
typography_spectrum: 0.9985874621197581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e1e6'
    - '#0ba29b'
    - '#9099a8'
    - '#104f47'
    - '#140903'
  brandStrength: 0.25
  lightness: 0.8608209080994129
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
